Simplify script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -30,37 +30,44 @@ set -e
 a() { sed 's/^/-----> /'; }
 i() { sed 's/^/       /'; }
 
-# Note: find out download URL with: apt-cache show graphviz | grep Filename
 case "$STACK" in
   heroku-16)
-    echo "Installing Graphviz version 2.38.0" | a
-    echo "(Ubuntu package graphviz_2.38.0-12ubuntu2.1_amd64.deb)" | i
-    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.38.0-12ubuntu2.1_amd64.deb' ;;
+    version="2.38.0"
+    pkg="graphviz_2.38.0-12ubuntu2.1_amd64.deb"
+    ;;
   cedar-14)
-    echo "Installing Graphviz version 2.36.0" | a
-    echo "(Ubuntu package graphviz_2.36.0-0ubuntu3.1_amd64.deb)" | i
-    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.36.0-0ubuntu3.1_amd64.deb' ;;
+    version="2.36.0"
+    pkg="graphviz_2.36.0-0ubuntu3.1_amd64.deb"
+     ;;
   *)
-    echo "Buildpack error: unsupported stack: $STACK" | a
-    exit 1 ;;
+    echo "Buildpack error: unsupported stack $STACK" | a
+    exit 1
+    ;;
 esac
+
+# Find out download URL with: apt-cache show graphviz | grep Filename
+url="http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/$pkg"
+
+echo "Installing Graphviz version $version" | a
+echo "$url" | i
 
 # Download package
 d=$(mktemp -dt XXXX)
-curl -s "$url" -o "$d"/pkg.deb
+curl -s "$url" -o "$d/pkg.deb"
 
 # Unpack and install binaries
-dpkg -x "$d"/pkg.deb "$d"
-mkdir -p "$1"/graphviz/bin
-mv "$d"/usr/bin/* "$1"/graphviz/bin
+dpkg -x "$d/pkg.deb" "$d"
+mkdir -p "$1/graphviz/bin"
+mv "$d"/usr/bin/* "$1/graphviz/bin"
 
 # .profile.d script adding /app/graphviz/bin to PATH and setting GRAPHVIZ_DOT
 # (scripts in .profile.d are sourced at dyno startup)
-mkdir -p "$1"/.profile.d
-cat <<'EOF' >"$1"/.profile.d/graphviz.sh
+mkdir -p "$1/.profile.d"
+cat <<'EOF' >"$1/.profile.d/graphviz.sh"
 PATH=/app/graphviz/bin:$PATH
 export GRAPHVIZ_DOT=/app/graphviz/bin/dot
 EOF
 
-echo "Graphviz binaries in /app/graphviz/bin and added to PATH" | a
+echo "Graphviz successfully installed to /app/graphviz/bin" | a
+echo "Verify with \"heroku run dot -V\""
 echo
