Rewrite
- Selection of Graphviz version dependent on runtime stack
- Simpler installation (install Graphviz package only, no dependencies)
- Setting of GRAPHVIZ_DOT environment variable

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,59 +1,68 @@
-#!/bin/bash
-# ------------------------------------------------------------------------------
-# Called by the build process (slug compiler): 
-#       compile <BUILD_DIR> <CACHE_DIR> <ENV_DIR>
-# ------------------------------------------------------------------------------
-# This executes in a special build environment where:
-# /app                          is the slug compiler
-# /tmp/build_<hash> (BUILD_DIR) contains the source code of our application,
-#                               and is going to be the slug of our app
-# ------------------------------------------------------------------------------
-# Summary: Downloads the Debian package 'graphviz' and all its dependent
-# packages, and installs them manually in our application slug.
-# ------------------------------------------------------------------------------
+#!/usr/bin/env bash
+#
+# Install Graphviz binaries to /app/graphviz/bin. The binaries are taken from
+# the official Ubuntu Debian Graphviz package for either Ubuntu 10.04 (if stack
+# is cedar) or Ubuntu 14.04 (if stack is cedar-14).
+#
+# The Ubuntu versions of both stacks already contain all the dependencies for
+# the Graphviz package (*), so it's safe to install it without apt-get.
+#
+# (*) Ubuntu 10.04 doesn't contain the libxaw7 and libxmu6 dependencies, but
+# they are used for X11 which anyway cannot be used on Heroku.
+#
+# Notes:
+# Check package deps: apt-cache depends graphviz
+# Package websites:   http://packages.ubuntu.com/trusty/graphviz   (14.04)
+#                     http://packages.ubuntu.com/lucid/graphviz    (10.04)
+#
+# ---
+#
+# The 'compile' script is executed by the slug compiler with three arguments:
+#   1. build_dir: location of your app directory on the build dyno
+#   2. cache_dir: directory on the build dyno that persists between builds
+#   3. env_dir:   directory holding all the app's config vars as files
+#
+# More information here: https://devcenter.heroku.com/articles/buildpack-api
+#
+# Daniel Weibel <daniel.weibel@unifr.ch> March 2015
+#------------------------------------------------------------------------------#
 
-# Exit whole script if any command returns a non-zero status (i.e. error)
 set -e
 
-# Holds our application source cde
-BUILD_DIR=$1    # /tmp/build_<hash> (subject to change...)
+a() { sed 's/^/-----> /'; }
+i() { sed 's/^/       /'; }
 
-# Location, relative to app root, where we want to install Graphviz to
-INSTALL_DIR=vendor/graphviz
-mkdir -p $BUILD_DIR/$INSTALL_DIR
+case "$STACK" in
+  cedar-14)
+    echo "Installing Graphviz version 2.36.0" | a
+    echo "(Ubuntu package graphviz_2.36.0-0ubuntu3.1_amd64.deb)" | i
+    # URL can be found out with: apt-cache show graphviz | grep Filename
+    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.36.0-0ubuntu3.1_amd64.deb' ;;
+  cedar)
+    echo "Installing Graphviz version 2.20.2" | a
+    echo "(Ubuntu package graphviz_2.20.2-8ubuntu3.2_amd64.deb)" | i
+    # URL can be found out with: apt-cache show graphviz | grep Filename
+    url='http://archive.ubuntu.com/ubuntu/pool/main/g/graphviz/graphviz_2.20.2-8ubuntu3.2_amd64.deb' ;;
+  *)
+    echo "Buildpack error: unsupported stack: $STACK" | a
+    exit 1 ;;
+esac
 
-# Creation of a custom apt environment. We have to do this, because we don't
-# have write permissions for the default apt environment. We intentionally do
-# it in an ephemeral location and not in the cache for keeping the cache small.
-APT=$HOME/apt   # HOME=/app in the build environment
-mkdir -p $APT/cache/archives/partial
-mkdir -p $APT/state/lists/partial
+# Download package
+d=$(mktemp -dt XXXX)
+curl -s "$url" -o "$d"/pkg.deb
 
-# apt-get options required by our custom apt environment
-OPTIONS="-o debug::nolocking=true -o dir::cache=$APT/cache -o dir::state=$APT/state"
+# Unpack and install binaries
+dpkg -x "$d"/pkg.deb "$d"
+mkdir -p "$1"/graphviz/bin
+mv "$d"/usr/bin/* "$1"/graphviz/bin
 
-# The mandatory apt-get update
-echo "-----> Updating Debian package lists (apt-get update)"
-apt-get $OPTIONS update >/dev/null 2>&1
+# .profile.d script for adding Graphviz binaries to PATH. (The GRAPHVIZ_DOT
+# variable is needed by some tools, e.g. PlantUML.)
+mkdir -p "$1"/.profile.d
+cat <<'EOF' >"$1"/.profile.d/graphviz.sh
+PATH=$PATH:/app/graphviz/bin
+export GRAPHVIZ_DOT=/app/graphviz/bin
+EOF
 
-# Download Graphviz package and its dependencies. The downloaded packages go to
-# $APT/cache/archives. The exact Graphviz version is determined by the version
-# in the 'graphviz' Debian package for the Linux version running on Heroku.
-echo "-----> Downloading Graphviz package and dependencies"
-apt-get $OPTIONS --download-only --assume-yes install graphviz >/dev/null 2>&1
-
-# Manual installation of the Graphviz package and its dependencies. This means
-# basically extracting all the packages to our installation directory.
-echo "-----> Installing Graphviz package and dependencies"
-cd $APT/cache/archives
-for PKG in $(ls *.deb); do
-    dpkg -x $PKG $BUILD_DIR/$INSTALL_DIR
-done
-
-# Add Graphviz to the runtime environment's PATH. Scripts in .profile.d/ are
-# sourced when the dyno running our application starts up.
-cd $BUILD_DIR
-mkdir -p .profile.d
-echo "PATH=\$HOME/$INSTALL_DIR/usr/bin:\$PATH" >.profile.d/graphviz.sh
-
-exit 0
+echo "Graphviz binaries in /app/graphviz/bin and added to PATH" | a
